// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: default-auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Otp           int32                  `protobuf:"varint,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_default_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_default_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_default_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetOtp() int32 {
	if x != nil {
		return x.Otp
	}
	return 0
}

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_default_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_default_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_default_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *AuthReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	mi := &file_default_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_default_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_default_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *UserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ResetValidatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetValidatorReq) Reset() {
	*x = ResetValidatorReq{}
	mi := &file_default_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetValidatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetValidatorReq) ProtoMessage() {}

func (x *ResetValidatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_default_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetValidatorReq.ProtoReflect.Descriptor instead.
func (*ResetValidatorReq) Descriptor() ([]byte, []int) {
	return file_default_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ResetValidatorReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ResetValidatorReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetReq) Reset() {
	*x = ResetReq{}
	mi := &file_default_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetReq) ProtoMessage() {}

func (x *ResetReq) ProtoReflect() protoreflect.Message {
	mi := &file_default_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetReq.ProtoReflect.Descriptor instead.
func (*ResetReq) Descriptor() ([]byte, []int) {
	return file_default_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ResetReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ResetReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_default_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_default_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_default_auth_proto_rawDescGZIP(), []int{5}
}

func (x *StandardResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_default_auth_proto protoreflect.FileDescriptor

const file_default_auth_proto_rawDesc = "" +
	"\n" +
	"\x12default-auth.proto\x12\x04auth\"R\n" +
	"\bLoginReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\x05R\x03otp\"[\n" +
	"\aAuthReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"?\n" +
	"\aUserReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"C\n" +
	"\x11ResetValidatorReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"V\n" +
	"\bResetReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\x10StandardResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x85\x03\n" +
	"\x1cDefaultAuthenticationService\x127\n" +
	"\fAuthenticate\x12\r.auth.AuthReq\x1a\x16.auth.StandardResponse\"\x00\x121\n" +
	"\x05Login\x12\x0e.auth.LoginReq\x1a\x16.auth.StandardResponse\"\x00\x12?\n" +
	"\x14RequestPasswordReset\x12\r.auth.UserReq\x1a\x16.auth.StandardResponse\"\x00\x12J\n" +
	"\x15ValidatePasswordReset\x12\x17.auth.ResetValidatorReq\x1a\x16.auth.StandardResponse\"\x00\x129\n" +
	"\rPasswordReset\x12\x0e.auth.ResetReq\x1a\x16.auth.StandardResponse\"\x00\x121\n" +
	"\x06Logout\x12\r.auth.UserReq\x1a\x16.auth.StandardResponse\"\x00B\n" +
	"Z\biam/authb\x06proto3"

var (
	file_default_auth_proto_rawDescOnce sync.Once
	file_default_auth_proto_rawDescData []byte
)

func file_default_auth_proto_rawDescGZIP() []byte {
	file_default_auth_proto_rawDescOnce.Do(func() {
		file_default_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_default_auth_proto_rawDesc), len(file_default_auth_proto_rawDesc)))
	})
	return file_default_auth_proto_rawDescData
}

var file_default_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_default_auth_proto_goTypes = []any{
	(*LoginReq)(nil),          // 0: auth.LoginReq
	(*AuthReq)(nil),           // 1: auth.AuthReq
	(*UserReq)(nil),           // 2: auth.UserReq
	(*ResetValidatorReq)(nil), // 3: auth.ResetValidatorReq
	(*ResetReq)(nil),          // 4: auth.ResetReq
	(*StandardResponse)(nil),  // 5: auth.StandardResponse
}
var file_default_auth_proto_depIdxs = []int32{
	1, // 0: auth.DefaultAuthenticationService.Authenticate:input_type -> auth.AuthReq
	0, // 1: auth.DefaultAuthenticationService.Login:input_type -> auth.LoginReq
	2, // 2: auth.DefaultAuthenticationService.RequestPasswordReset:input_type -> auth.UserReq
	3, // 3: auth.DefaultAuthenticationService.ValidatePasswordReset:input_type -> auth.ResetValidatorReq
	4, // 4: auth.DefaultAuthenticationService.PasswordReset:input_type -> auth.ResetReq
	2, // 5: auth.DefaultAuthenticationService.Logout:input_type -> auth.UserReq
	5, // 6: auth.DefaultAuthenticationService.Authenticate:output_type -> auth.StandardResponse
	5, // 7: auth.DefaultAuthenticationService.Login:output_type -> auth.StandardResponse
	5, // 8: auth.DefaultAuthenticationService.RequestPasswordReset:output_type -> auth.StandardResponse
	5, // 9: auth.DefaultAuthenticationService.ValidatePasswordReset:output_type -> auth.StandardResponse
	5, // 10: auth.DefaultAuthenticationService.PasswordReset:output_type -> auth.StandardResponse
	5, // 11: auth.DefaultAuthenticationService.Logout:output_type -> auth.StandardResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_default_auth_proto_init() }
func file_default_auth_proto_init() {
	if File_default_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_default_auth_proto_rawDesc), len(file_default_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_default_auth_proto_goTypes,
		DependencyIndexes: file_default_auth_proto_depIdxs,
		MessageInfos:      file_default_auth_proto_msgTypes,
	}.Build()
	File_default_auth_proto = out.File
	file_default_auth_proto_goTypes = nil
	file_default_auth_proto_depIdxs = nil
}
